### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by NeonMoondust** [313hemant313/capacitor-plugin-incoming-call#1]
`CallDetector.addListener('callStateChange', state => {
      console.log(state);
      this.debug += 'passed ';
    });`

Been trying in many ways with no success, would you share an example of how to use it ? starting from the import just a quick example ? Also if require any permissions ?

**Comment by 313hemant313** [comment]
Sure give me sometime will try to come up with an example.

In this I am using android TelephonyManager so please check required permissions. Most probably this is required for sure READ_PHONE_STATE permission.

**Comment by 313hemant313** [comment]
@NeonMoondust

This is how you can use the plugin in any project.

## Usage

Typescipt side changes:
```bash
console.log('### Test CallDetector plugin ###');
CallDetector.detectCallState({ action: 'ACTIVATE' }).then(x => console.log(x)).catch(e => console.error(e));
CallDetector.addListener('callStateChange', res => {
  console.log('### Listening to callStateChange ###');
  console.log(res);
});
```

Android side changes:
```bash
public class MainActivity extends BridgeActivity {

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    String[] PERMISSIONS = {
      android.Manifest.permission.READ_PHONE_STATE,
      android.Manifest.permission.READ_CALL_LOG
    };

    ActivityCompat.requestPermissions(MainActivity.this,
      PERMISSIONS,
      0);
  }

}
```
