### ISSUE TITLE
Capacitor V5 Support?

### ISSUE THREAD

**Issue by devhus** [313hemant313/capacitor-plugin-incoming-call#12]
Is this package supports version 5 of Capacitor yet?

**Comment by 313hemant313** [comment]
@devhus I have made the changes, can you please run a quick test. 
Will merge the PR once you give go ahead.

https://github.com/313hemant313/capacitor-plugin-incoming-call/pull/13

**Comment by devhus** [comment]
@313hemant313 I have tried the changes and it seems to be working just fine.
there are also some deprecated methods warnings that started to pop up in the build phase , so be careful about these

**Comment by 313hemant313** [comment]
@devhus  PR merged.

**Comment by devhus** [comment]
> @devhus  PR merged.

Dont forget to publish on npm

**Comment by 313hemant313** [comment]
Published 👍 

+ capacitor-plugin-incoming-call@0.0.7
