### ISSUE TITLE
Pass phone number to callbacks

### ISSUE THREAD

**Issue by veneliniliev** [313hemant313/capacitor-plugin-incoming-call#14]
can the phone number also be added to the call status?

**Comment by 313hemant313** [comment]
@veneliniliev I have created the change but not able to test it, can you please help with the testing.

https://github.com/313hemant313/capacitor-plugin-incoming-call/pull/15

**Comment by 313hemant313** [comment]
Latest version released: capacitor-plugin-incoming-call@0.0.9
