### ISSUE TITLE
Capacitor 4 support?

### ISSUE THREAD

**Issue by AnastasiosF** [313hemant313/capacitor-plugin-incoming-call#2]
Capacitor 4 support?

**Comment by 313hemant313** [comment]
Hey, Sorry not getting any time for this. Will be happy if anyone raises a pr.

**Comment by 313hemant313** [comment]
@AnastasiosF Added new version with Capacitor 4 support.

https://www.npmjs.com/package/capacitor-plugin-incoming-call?activeTab=versions
