### ISSUE TITLE
The incoming call number not returing

### ISSUE THREAD

**Issue by bmondal** [313hemant313/capacitor-plugin-incoming-call#22]
Hello,

By using this plugin I'm getting the call state but not getting the incoming call number. Please tell me how to get the incoming call number. I'm using the below code

CallDetector.detectCallState({ action: 'ACTIVATE' }).then(x => console.log(x)).catch(e => console.error(e));
    CallDetector.addListener('callStateChange', res => {
      console.log('### Listening to callStateChange ###');
      console.log(res);
      this.callerStaeData = res;
    });
  }

**Comment by 313hemant313** [comment]
Please check https://github.com/313hemant313/capacitor-plugin-incoming-call/issues/14

This also https://github.com/313hemant313/capacitor-plugin-incoming-call/pull/15

**Comment by bmondal** [comment]
> Please check #14
> 
> This also #15

I checked all of these but nothing is working. Can you please tell me how to get the incoming number while it's incoming? As per the code there has set the TelephonyManager.EXTRA_INCOMING_NUMBER but it's not working

**Comment by 313hemant313** [comment]
Ohh i think there are 2 fields incoming and outgoing numbers, no value is coming ?

https://github.com/313hemant313/capacitor-plugin-incoming-call/blob/8f123cd1bd2afc94f20dbfcf7bd0d48214b47a9b/src/definitions.ts
