### ISSUE TITLE
addListner commented out in android

### ISSUE THREAD

**Issue by ItayHarshuv** [313hemant313/capacitor-plugin-incoming-call#3]
addListner does not work. When diving into the implementation I saw addListner file commented out. Is is suppose to?

**Comment by 313hemant313** [comment]
CallStateListener class is not required.

Can you please share some logs so that i can check ?

**Comment by ItayHarshuv** [comment]
My code: 
`CallDetector.detectCallState({action: 'ACTIVATE'});
CallDetector.addListener("callStateChange", () => {
      console.log("state change")
    })`

and in console:

![image](https://user-images.githubusercontent.com/72868775/209675420-ca615d8d-2fce-4058-9772-415315c7f79a.png)

However, nothing happens when I call the phone after the listner has been added. Did I miss something?

**Comment by 313hemant313** [comment]
@ItayHarshuv I have added the usage section in the readme please check.

Also i have published new changes which i have tested out.

**Comment by ItayHarshuv** [comment]
Thank you, works for me now!
