### ISSUE TITLE
Clear event listener

### ISSUE THREAD

**Issue by devhus** [313hemant313/capacitor-plugin-incoming-call#7]
Please add an API method to clear the added event listeners.

The problem:
After using 
```
CallDetector.addListener('callStateChange', res => {
  console.log('### Listening to callStateChange ###');
  console.log(res);
});
``` 
The event listener will be working in the background until the app is closed, 
And so if you called ``CallDetector.addListener`` within a mounting phase of a component the event will be listener registered every time the component mounts, Which creates a huge problem where the event will be called many times every time the call state changes.

The solution:
Create an API method ``CallDetector.clearListeners`` to remove one or all of the registered listeners.

**Comment by 313hemant313** [comment]
There is one remove listener method already, it seems this should resolve the issue.

```    /**
     * Exported plugin call to remove a listener from this plugin
     * @param call
     */
    @SuppressWarnings("unused")
    @PluginMethod(returnType = PluginMethod.RETURN_NONE)
    public void removeListener(PluginCall call) {
        String eventName = call.getString("eventName");
        String callbackId = call.getString("callbackId");
        PluginCall savedCall = bridge.getSavedCall(callbackId);
        if (savedCall != null) {
            removeEventListener(eventName, savedCall);
            bridge.releaseCall(savedCall);
        }
    }
```

**Comment by devhus** [comment]
Sorry, I am new to Ionic and might misunderstand that one.
It's good that the API method does exist but it's not mentioned in the plugin doc nor in the typescript definition so it's hard to figure it out.
Could you please update the readme file and typescript files to allow access to these methods?

Also when calling ``removeListener`` what does the argument ``PluginCall call`` stands for(where to get it to pass it to the function)?

**Comment by 313hemant313** [comment]
I think this should help.
https://forum.ionicframework.com/t/calling-addlistener-in-typescript-to-add-event-listener-to-capacitor-plugin/220224
